### ISSUE TITLE
How to use dynamic imports with Vite?

### ISSUE THREAD

**Issue by retroriff** [nuxt-community/svg-module#93] opened 2022-08-27 17:31 UTC
On Vite `require` doesn't work because it's webpack-only.

```
<template>
  <div v-html="require(`../assets/${name}.svg?raw`)" />
</template>

<script>
  export default {
    props: {
      name: { type: String, default: "image" },
    },
  };
</script>
```

Is there any alternative for Vite?

**Comment by manuelodelain** [comment] 2022-08-30 07:40
Duplicate of #86

**Closed as completed** 2022-08-31 19:24 UTC
